version: '3'
services:
  postgres-madrid:
    image: postgres:11
    container_name: postgres-tutorial
    command: postgres -c 'max_connections=300'
    ports:
        - "5433:5433"
    environment:
      POSTGRES_DB: tutorial
      POSTGRES_USER: tutorial
      POSTGRES_PASSWORD: 1234